# -*- coding: utf-8 -*-
"""#18~19생성_분기/반기생성

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YPjF7sKVERwtICgzJZcTdKlRhWUBdnxX

### 필요 열 생성 
- 분기
- 반기

**분석 데이터 생성 후, 엑셀 작업**
- #18 Graph. 관평5 단지의 공용 전기료 증감 추이 
- #19 Graph. 지족20 단지의 공용 전기료 증감 추이

###필요 열 생성
- 분기
- 반기
"""

|import pandas as pd

df = pd.read_csv("아파트전체정보_ver0.2.csv", engine = 'python')

df.columns

df['반기'] = ''
df['분기'] = ''

df['부과년월'][0]

df.info()

for i in range(len(df)):
    if df['부과월'][i] in [1,2,3,4,5,6]:
        df['반기'][i] = '상반기'
    else:
        df['반기'][i] = '하반기'

for i in range(len(df)):
    if df['부과월'][i] in [1,2,3]:
        df['분기'][i] = 1
    elif df['부과월'][i] in [4,5,6]:
        df['분기'][i] = 2
    elif df['부과월'][i] in [7, 8, 9]:
        df['분기'][i] = 3
    else:
        df['분기'][i] = 4

df.head()

df.to_csv("아파트전체정보_ver0.2.csv", encoding = 'utf-8')